# version: 1.0.0
# Homogenized gradient bar theme with comprehensive features

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0)\
[](fg:#769ff0 bg:#16181d)\
$fill\
[░▒▓](fg:#1d2230 bg:#16181d)\
$cmd_duration\
$hostname\
$localip\
$username\
$sudo\
$jobs\
$shell\
$env_var\
$shlvl\
$battery\
$status\
$os\
$time\
[](fg:#394260 bg:#16181d)\
$git_branch\
$git_status\
$git_metrics\
$git_commit\
$git_state\
[](fg:#394260 bg:#212736)\
$nodejs\
$python\
$rust\
$golang\
$java\
$lua\
$ruby\
$swift\
$php\
$dart\
$deno\
$elixir\
$elm\
$haskell\
$julia\
$kotlin\
$scala\
$nim\
$crystal\
$ocaml\
$zig\
$vlang\
$terraform\
$c\
$cpp\
$cmake\
$gradle\
$meson\
$helm\
$package\
$nix_shell\
$guix_shell\
$conda\
$pixi\
$spack\
$vagrant\
$pulumi\
$buf\
[](fg:#212736 bg:#1d2230)\
$docker_context\
$kubernetes\
$aws\
$azure\
$gcloud\
$openstack\
$memory_usage\
$container\
\n$character"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[❯](bold italic bright-yellow)"
error_symbol = "[❯](italic purple)"
vimcmd_symbol = "[❮](italic dimmed green)"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "⌂"
read_only = " ◈"
use_os_path_sep = true
repo_root_style = 'fg:#e3e5e5 bg:#769ff0 bold'
repo_root_format = '[ $before_root_path$repo_root$path ]($repo_root_style)'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "󰇚 "
"Music" = "󰝚 "
"Pictures" = " "
"Videos" = " "
"Projects" = " "
"Code" = " "
"Desktop" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'
truncation_length = 15
truncation_symbol = "⋯"
ignore_branches = ["main", "master"]

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
conflicted = '◪'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
untracked = '◌'
stashed = '◃'
modified = '●'
staged = '▪'
renamed = '◎'
deleted = '✕'

[git_metrics]
format = '[[+$added~$deleted ](fg:#769ff0 bg:#394260)]($style)'
added_style = 'fg:#769ff0 bg:#394260'
deleted_style = 'fg:#769ff0 bg:#394260'
ignore_submodules = true
disabled = false

[git_commit]
commit_hash_length = 4
tag_symbol = "ﰖ"
format = "[[($hash$tag) ](fg:#769ff0 bg:#394260)]($style)"
style = "bg:#394260"
only_detached = false

[git_state]
format = '[[($state) ](fg:#769ff0 bg:#394260)]($style)'
style = "bg:#394260"

# Language/Runtime configurations
[nodejs]
symbol = "󰎙 "
style = "bg:#212736"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'
detect_files = ["package.json", ".node-version", "package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]

[python]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'
version_format = "${raw}"

[rust]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'
version_format = "${raw}"

[golang]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[java]
symbol = "󰅶 "
style = "bg:#212736"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[lua]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
version_format = "${raw}"

[ruby]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
version_format = "${raw}"

[swift]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
version_format = "${raw}"

[php]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[dart]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[deno]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
version_format = "${raw}"

[elixir]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[elm]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[haskell]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[julia]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[kotlin]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[scala]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[nim]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[crystal]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[ocaml]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[zig]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[vlang]
symbol = "Vlang "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[terraform]
symbol = "󱁢 "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[c]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[cpp]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[cmake]
symbol = "CMake "
style = "bg:#212736"
format = '[[ $symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[gradle]
symbol = "Gradle"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[meson]
symbol = "Meson"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[helm]
symbol = "Helm"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[package]
symbol = "Package"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
version_format = "${raw}"

[nix_shell]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($name) ](fg:#769ff0 bg:#212736)]($style)'
impure_msg = "impure"
pure_msg = "pure"

[guix_shell]
symbol = "GShell"
style = "bg:#212736"
format = '[[ $symbol ($name) ](fg:#769ff0 bg:#212736)]($style)'

[conda]
symbol = "Conda"
style = "bg:#212736"
format = '[[ $symbol ($environment) ](fg:#769ff0 bg:#212736)]($style)'

[pixi]
symbol = "Pixi"
style = "bg:#212736"
format = '[[ $symbol ($environment) ](fg:#769ff0 bg:#212736)]($style)'

[spack]
symbol = "Spack"
style = "bg:#212736"
format = '[[ $symbol ($environment) ](fg:#769ff0 bg:#212736)]($style)'

[vagrant]
symbol = "Vagrant"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[pulumi]
symbol = "Pulumi"
style = "bg:#212736"
format = '[[ $symbol ($username) ](fg:#769ff0 bg:#212736)]($style)'

[buf]
symbol = "Buf"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# Infrastructure and cloud (darker section)
[docker_context]
symbol = " "
style = "bg:#1d2230"
format = '[[ $symbol ($context) ](fg:#a0a9cb bg:#1d2230)]($style)'

[kubernetes]
symbol = "󱃾 "
style = "bg:#1d2230"
format = '[[ $symbol ($context) ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[aws]
symbol = " AWS "
style = "bg:#1d2230"
format = '[[ $symbol ($profile) ](fg:#a0a9cb bg:#1d2230)]($style)'
disabled = false

[azure]
symbol = " AZURE "
style = "bg:#1d2230"
format = '[[ $symbol ($subscription) ](fg:#a0a9cb bg:#1d2230)]($style)'

[gcloud]
symbol = " Gcloud "
style = "bg:#1d2230"
format = '[[ $symbol ($project) ](fg:#a0a9cb bg:#1d2230)]($style)'

[openstack]
symbol = "OStack "
style = "bg:#1d2230"
format = '[[ $symbol ($cloud) ](fg:#a0a9cb bg:#1d2230)]($style)'

[memory_usage]
symbol = "MEM "
style = "bg:#1d2230"
format = '[[ $symbol ${ram} ](fg:#a0a9cb bg:#1d2230)]($style)'
threshold = 70

[container]
symbol = "Cont "
style = "bg:#1d2230"
format = '[[ $symbol ($name) ](fg:#a0a9cb bg:#1d2230)]($style)'

# System information (darkest section)
[cmd_duration]
format = "[[ $duration ](fg:#8a8eab bg:#16181d)]($style)"
style = "bg:#16181d"
min_time = 0
show_milliseconds = false

[hostname]
format = "[[ $hostname ](fg:#8a8eab bg:#16181d)]($style)"
style = "bg:#16181d"
trim_at = ".companyname.com"
disabled = false

[localip]
ssh_only = true
format = "[[ $localipv4 ](fg:#8a8eab bg:#16181d)]($style)"
style = "bg:#16181d"
disabled = false

[username]
style_user = "fg:#8a8eab bg:#16181d"
style_root = "fg:#ff6b6b bg:#16181d"
format = "[[ $user ](fg:#8a8eab bg:#16181d)]($style)"
disabled = false
show_always = false

[sudo]
format = "[[ sudo ](fg:#ff6b6b bg:#16181d)]($style)"
style = "bg:#16181d"
disabled = false

[jobs]
format = "[[ $symbol$number ](fg:#8a8eab bg:#16181d)]($style)"
style = "bg:#16181d"
symbol = ""

[shell]
format = "[[ $indicator ](fg:#8a8eab bg:#16181d)]($style)"
style = "bg:#16181d"
disabled = false

[env_var.VIMSHELL]
format = "[[ $env_value ](fg:#8a8eab bg:#16181d)]($style)"
style = "bg:#16181d"

[shlvl]
format = "[[ $shlvl ](fg:#8a8eab bg:#16181d)]($style)"
style = "bg:#16181d"
disabled = false


[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
unknown_symbol = "?"
empty_symbol = " "

[[battery.display]]
threshold = 20
style = "fg:#ff6b6b bg:#16181d"

[[battery.display]]
threshold = 60
style = "fg:#ffd93d bg:#16181d"

[[battery.display]]
threshold = 100
style = "fg:#8a8eab bg:#16181d"


[status]
format = '[[ ✘$status ](fg:#ff6b6b bg:#16181d)]($style)'
style = "bg:#16181d"
disabled = false

[os]
format = "[[ $name ](fg:#8a8eab bg:#16181d)]($style)"
style = "bg:#16181d"
disabled = false

[time]
disabled = false
time_format = "%R"
style = "bg:#16181d"
format = '[[  $time ](fg:#8a8eab bg:#16181d)]($style)'
